# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from Protos import files_pb2 as Protos_dot_files__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class FilesStub(object):
    """Service for work with files and directories
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/Files.Files/Create',
                request_serializer=Protos_dot_files__pb2.CreateRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.Move = channel.unary_unary(
                '/Files.Files/Move',
                request_serializer=Protos_dot_files__pb2.MoveRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.Remove = channel.unary_unary(
                '/Files.Files/Remove',
                request_serializer=Protos_dot_files__pb2.RemoveRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.OpenInFileManager = channel.unary_unary(
                '/Files.Files/OpenInFileManager',
                request_serializer=Protos_dot_files__pb2.OpenInFileManagerRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.CopyPath = channel.unary_unary(
                '/Files.Files/CopyPath',
                request_serializer=Protos_dot_files__pb2.CopyPathRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.Exists = channel.unary_unary(
                '/Files.Files/Exists',
                request_serializer=Protos_dot_files__pb2.ExistsRequest.SerializeToString,
                response_deserializer=Protos_dot_files__pb2.ExistsResponse.FromString,
                )
        self.Copy = channel.unary_unary(
                '/Files.Files/Copy',
                request_serializer=Protos_dot_files__pb2.CopyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.Paste = channel.unary_unary(
                '/Files.Files/Paste',
                request_serializer=Protos_dot_files__pb2.PasteRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetFileContent = channel.unary_unary(
                '/Files.Files/GetFileContent',
                request_serializer=Protos_dot_files__pb2.GetFileContentRequest.SerializeToString,
                response_deserializer=Protos_dot_files__pb2.GetFileContentResponse.FromString,
                )


class FilesServicer(object):
    """Service for work with files and directories
    """

    def Create(self, request, context):
        """Creates file or directory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Move(self, request, context):
        """Moves/renames file or directory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Removes file or directory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenInFileManager(self, request, context):
        """Opens file/directory in file manager (in Windows: explorer.exe, Linux-based: xdg-open, OSX: open)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CopyPath(self, request, context):
        """
        Copies file/directory path to clipboard. For Linux-based must to be installed: 
        xsel(for X11 session), wl-clipboard(for Wayland session)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exists(self, request, context):
        """Checks for the existence of a file/directory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Copy(self, request, context):
        """Copies file/directory to temp directory (<temp-folder-path>/Barkditor/Copied)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Paste(self, request, context):
        """Pastes file/directory from <temp-folder-path>/Barkditor/Copied to specified path
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileContent(self, request, context):
        """Returns file content and content type by particular path
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FilesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=Protos_dot_files__pb2.CreateRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Move': grpc.unary_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=Protos_dot_files__pb2.MoveRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=Protos_dot_files__pb2.RemoveRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'OpenInFileManager': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenInFileManager,
                    request_deserializer=Protos_dot_files__pb2.OpenInFileManagerRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CopyPath': grpc.unary_unary_rpc_method_handler(
                    servicer.CopyPath,
                    request_deserializer=Protos_dot_files__pb2.CopyPathRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Exists': grpc.unary_unary_rpc_method_handler(
                    servicer.Exists,
                    request_deserializer=Protos_dot_files__pb2.ExistsRequest.FromString,
                    response_serializer=Protos_dot_files__pb2.ExistsResponse.SerializeToString,
            ),
            'Copy': grpc.unary_unary_rpc_method_handler(
                    servicer.Copy,
                    request_deserializer=Protos_dot_files__pb2.CopyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Paste': grpc.unary_unary_rpc_method_handler(
                    servicer.Paste,
                    request_deserializer=Protos_dot_files__pb2.PasteRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetFileContent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileContent,
                    request_deserializer=Protos_dot_files__pb2.GetFileContentRequest.FromString,
                    response_serializer=Protos_dot_files__pb2.GetFileContentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Files.Files', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Files(object):
    """Service for work with files and directories
    """

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Files.Files/Create',
            Protos_dot_files__pb2.CreateRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Files.Files/Move',
            Protos_dot_files__pb2.MoveRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Files.Files/Remove',
            Protos_dot_files__pb2.RemoveRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OpenInFileManager(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Files.Files/OpenInFileManager',
            Protos_dot_files__pb2.OpenInFileManagerRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CopyPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Files.Files/CopyPath',
            Protos_dot_files__pb2.CopyPathRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Exists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Files.Files/Exists',
            Protos_dot_files__pb2.ExistsRequest.SerializeToString,
            Protos_dot_files__pb2.ExistsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Copy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Files.Files/Copy',
            Protos_dot_files__pb2.CopyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Paste(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Files.Files/Paste',
            Protos_dot_files__pb2.PasteRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFileContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Files.Files/GetFileContent',
            Protos_dot_files__pb2.GetFileContentRequest.SerializeToString,
            Protos_dot_files__pb2.GetFileContentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
