# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from Protos import projectFiles_pb2 as Protos_dot_projectFiles__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class ProjectFilesStub(object):
    """Service for project file tree output
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetProjectPath = channel.unary_unary(
                '/ProjectFiles.ProjectFiles/SetProjectPath',
                request_serializer=Protos_dot_projectFiles__pb2.SetProjectPathRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetProjectPath = channel.unary_unary(
                '/ProjectFiles.ProjectFiles/GetProjectPath',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Protos_dot_projectFiles__pb2.GetProjectPathResponse.FromString,
                )


class ProjectFilesServicer(object):
    """Service for project file tree output
    """

    def SetProjectPath(self, request, context):
        """Returns file tree by directory path and save this path
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProjectPath(self, request, context):
        """Returns saved directory path
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProjectFilesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetProjectPath': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProjectPath,
                    request_deserializer=Protos_dot_projectFiles__pb2.SetProjectPathRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetProjectPath': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProjectPath,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Protos_dot_projectFiles__pb2.GetProjectPathResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ProjectFiles.ProjectFiles', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProjectFiles(object):
    """Service for project file tree output
    """

    @staticmethod
    def SetProjectPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ProjectFiles.ProjectFiles/SetProjectPath',
            Protos_dot_projectFiles__pb2.SetProjectPathRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProjectPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ProjectFiles.ProjectFiles/GetProjectPath',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Protos_dot_projectFiles__pb2.GetProjectPathResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
